# Fine tunes whole model on UCF101

dataset: '/home/coala/mestrado/datasets/UCF101/split01/'
classes: '/home/coala/mestrado/datasets/UCF101/classes_index.csv'
annotations: '/home/coala/mestrado/datasets/UCF101/split01/frame_info.csv'
n_classes: 101
epochs: 300
batch_size: 32
train_only_last: False
learn_rate: 0.001
l2_reg: 0.0005
dropout: 0.85
momentum: 0.9
weights: 'imagenet'
