# File that defines a training routine

dataset: 'path to dataset'
classes: 'path to classes file'
epochs: 200
batch_size: 32
learn_rate: 1e-5
l2_reg: 1e-5
dropout: 0.85
optmizer: 'SDG' # 'SDG' or 'Adam'
momentum: 0.9
weights: 'imagenet'
